BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi/V1/Boundary/Request/CreateReferralRequest.cs
BrokerageApi/V1/Boundary/Response/ReferralResponse.cs
BrokerageApi/V1/Factories/EntityFactory.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Infrastructure/Migrations/20220325122546_AddUrgentSinceToReferrals.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220325122546_AddUrgentSinceToReferrals.cs
BrokerageApi/V1/Infrastructure/Referral.cs

This marks the referral as urgent if it is not null.

Add UrgentSince property to CreateReferralRequest

---

BrokerageApi.Tests/V1/Controllers/ReferralsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/UseCase/AssignBrokerToReferralUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Boundary/Request/AssignBrokerRequest.cs
BrokerageApi/V1/Controllers/ReferralsController.cs
BrokerageApi/V1/Infrastructure/DbSaver.cs
BrokerageApi/V1/Infrastructure/IDbSaver.cs
BrokerageApi/V1/UseCase/AssignBrokerToReferralUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IAssignBrokerToReferralUseCase.cs

https://hackney.atlassian.net/browse/FBT-39
This PR does not apply any user checks on who is doing the assigning or whether the assignee is actually a broker within the system. A follow up PR needs to be made once a current user service is created as part of the [authorisation ticket][1].
[1]: https://hackney.atlassian.net/browse/FBT-7

Add endpoint to assign a referral to a broker

---

BrokerageApi.Tests/V1/Controllers/ReferralsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/UseCase/ReassignBrokerToReferralUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/ReferralsController.cs
BrokerageApi/V1/UseCase/Interfaces/IReassignBrokerToReferralUseCase.cs
BrokerageApi/V1/UseCase/ReassignBrokerToReferralUseCase.cs

Leaves the current status as-is.

Add reassign referral endpoint

---

BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi/V1/Boundary/Request/CreateReferralRequest.cs
BrokerageApi/V1/Boundary/Response/ReferralResponse.cs
BrokerageApi/V1/Factories/EntityFactory.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Infrastructure/Migrations/20220412085731_AddNoteToReferral.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220412085731_AddNoteToReferral.cs
BrokerageApi/V1/Infrastructure/Referral.cs

This holds the next step notes from the core pathways tool.

Add note field to referral entity

---

BrokerageApi.Tests/DatabaseTests.cs
BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/Gateways/CarePackageGatewayTests.cs
BrokerageApi.Tests/V1/UseCase/CreateElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/GetCarePackageByIdUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Boundary/Response/CarePackageResponse.cs
BrokerageApi/V1/Boundary/Response/ElementTypeResponse.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Gateways/CarePackageGateway.cs
BrokerageApi/V1/Gateways/Interfaces/ICarePackageGateway.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/CarePackage.cs
BrokerageApi/V1/Infrastructure/Element.cs
BrokerageApi/V1/Infrastructure/Migrations/20220430071539_CreateCarePackageViews.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220430071539_CreateCarePackageViews.cs
BrokerageApi/V1/Infrastructure/ReferralElement.cs
BrokerageApi/V1/UseCase/CreateElementUseCase.cs
BrokerageApi/V1/UseCase/GetCarePackageByIdUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IGetCarePackageByIdUseCase.cs

The care package entity is a pseudo-entitity made up of the referral's elements and some aggregate data.

Add endpoint for fetching care package

---

BrokerageApi.Tests/IntegrationTests.cs
BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/Gateways/ReferralGatewayTests.cs
BrokerageApi.Tests/V1/Helpers/FixtureHelpers.cs
BrokerageApi.Tests/V1/Helpers/MockDbSaver.cs
BrokerageApi.Tests/V1/UseCase/CreateElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/DeleteElementUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Gateways/Interfaces/IReferralGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/UseCase/DeleteElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IDeleteElementUseCase.cs

[Add a link to the JIRA ticket that the changes in this PR describe.](https://hackney.atlassian.net/browse/FBT-133)

Add Delete Element

---

BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/Gateways/AuditGatewayTests.cs
BrokerageApi.Tests/V1/UseCase/AssignBrokerToReferralUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/Mocks/MockAuditGateway.cs
BrokerageApi.Tests/V1/UseCase/ReassignBrokerToReferralUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Gateways/AuditGateway.cs
BrokerageApi/V1/Gateways/Interfaces/IAuditGateway.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditEvent.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditMetadataBase.cs
BrokerageApi/V1/Infrastructure/AuditEvents/ReferralAssignmentAuditEventMetadata.cs
BrokerageApi/V1/Infrastructure/BrokerageClaimsTransformer.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/Migrations/20220512155046_AuditEvent.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220512155046_AuditEvent.cs
BrokerageApi/V1/Services/Interfaces/IUserService.cs
BrokerageApi/V1/Services/UserService.cs
BrokerageApi/V1/UseCase/AssignBrokerToReferralUseCase.cs
BrokerageApi/V1/UseCase/ReassignBrokerToReferralUseCase.cs

https://hackney.atlassian.net/browse/FBT-131
Adding AuditEvent table and implementing on assignment changes

Add AuditEvent table and implement on assignment chnage

---

BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/Controllers/ElementsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/Helpers/FixtureHelpers.cs
BrokerageApi.Tests/V1/UseCase/EndElementUseCaseTests.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Controllers/ElementsController.cs
BrokerageApi/V1/Gateways/AuditGateway.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditEvent.cs
BrokerageApi/V1/Infrastructure/AuditEvents/ReferralAssignmentAuditEventMetadata.cs
BrokerageApi/V1/Infrastructure/Migrations/20220518144830_AuditEventEnum.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220518144830_AuditEventEnum.cs
BrokerageApi/V1/UseCase/EndElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IEndElementUseCase.cs

Add audit trail
Moved to correct URI and respect referral existence
https://hackney.atlassian.net/browse/FBT-149

FBT-149 End Element

---

BrokerageApi.Tests/IntegrationTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/Helpers/FixtureHelpers.cs
BrokerageApi.Tests/V1/UseCase/CreateElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/DeleteElementUseCaseTests.cs
BrokerageApi/V1/Gateways/CarePackageGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditEvent.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditEventType.cs
BrokerageApi/V1/UseCase/CreateElementUseCase.cs
BrokerageApi/V1/UseCase/DeleteElementUseCase.cs

https://hackney.atlassian.net/browse/FBT-148
Made Edit and Delete element respect parent element

Fbt 148 edit element

---

BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/UseCase/CancelElementUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Infrastructure/ElementStatus.cs
BrokerageApi/V1/Infrastructure/Migrations/20220520074458_AddCancelledElementStatus.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220520074458_AddCancelledElementStatus.cs
BrokerageApi/V1/UseCase/CancelElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/ICancelElementUseCase.cs

https://hackney.atlassian.net/browse/FBT-153
Add endpoint for cancelling an element

Fbt 153 - Add Cancel Element end point

---

BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/E2ETests/ServiceTests.cs
BrokerageApi.Tests/V1/UseCase/CancelElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/EditElementUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Boundary/Request/EditElementRequest.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Factories/EntityFactory.cs
BrokerageApi/V1/Gateways/ServiceGateway.cs
BrokerageApi/V1/UseCase/CancelElementUseCase.cs
BrokerageApi/V1/UseCase/EditElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/ICancelElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IEditElementUseCase.cs

https://hackney.atlassian.net/browse/FBT-173
Added endpoint for editing elements in progress

Fbt 173 edit element

---

BrokerageApi/V1/Infrastructure/Migrations/20220524101056_ReferralStatusAddEndedAndActive.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220524101056_ReferralStatusAddEndedAndActive.cs
BrokerageApi/V1/Infrastructure/Migrations/20220524102231_CarePackageStatusView.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220524102231_CarePackageStatusView.cs
BrokerageApi/V1/Infrastructure/ReferralStatus.cs

Laying the foundation of future care package work

Create view for care package status

---

BrokerageApi/V1/Boundary/Response/ServiceResponse.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/Migrations/20220531074432_AddHasProvisionalClientContributionsToService.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220531074432_AddHasProvisionalClientContributionsToService.cs
BrokerageApi/V1/Infrastructure/Service.cs
data/seeds/services.csv

This controls whether the frontend should show the option to the broker of add provisional client contributions.
https://hackney.atlassian.net/browse/FBT-199

Add HasProvisionClientContributions to Service

---

README.md

https://hackney.atlassian.net/browse/FBT-191
Creating an MVP readme for our API

Readme - first version

---

BrokerageApi.Tests/DatabaseTests.cs
BrokerageApi.Tests/IntegrationTests.cs
BrokerageApi.Tests/V1/Controllers/UsersControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/UserTests.cs
BrokerageApi.Tests/V1/Gateways/UserGatewayTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/CreateElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/DeleteElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/EditElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/StartCarePackageUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/GetAssignedReferralsUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/GetCurrentUserUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/UsersController.cs
BrokerageApi/V1/Gateways/Interfaces/IUserGateway.cs
BrokerageApi/V1/Gateways/UserGateway.cs
BrokerageApi/V1/Infrastructure/BrokerageClaimsTransformer.cs
BrokerageApi/V1/Services/Interfaces/IUserService.cs
BrokerageApi/V1/Services/UserService.cs
BrokerageApi/V1/UseCase/CarePackageElements/CreateElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/DeleteElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/EditElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/StartCarePackageUseCase.cs
BrokerageApi/V1/UseCase/GetAssignedReferralsUseCase.cs
BrokerageApi/V1/UseCase/GetCurrentUserUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IGetCurrentUserUseCase.cs

https://hackney.atlassian.net/browse/FBT-189

Get current user

---

BrokerageApi/V1/Boundary/Response/ElementTypeResponse.cs
BrokerageApi/V1/Boundary/Response/ProviderResponse.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/ElementBillingType.cs
BrokerageApi/V1/Infrastructure/ElementType.cs
BrokerageApi/V1/Infrastructure/ElementTypeType.cs
BrokerageApi/V1/Infrastructure/Migrations/20220531144023_AddBillingToElementType.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220531144023_AddBillingToElementType.cs
BrokerageApi/V1/Infrastructure/Migrations/20220606064242_AddTypeToElementType.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220606064242_AddTypeToElementType.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608055505_AddCedarSiteToProvider.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608055505_AddCedarSiteToProvider.cs
BrokerageApi/V1/Infrastructure/Provider.cs
data/seeds/element_types.csv
data/seeds/services.csv

https://hackney.atlassian.net/browse/FBT-192
https://hackney.atlassian.net/browse/FBT-194

Add schema and seed data to represent care charges

---

BrokerageApi.Tests/DatabaseTests.cs
BrokerageApi.Tests/IntegrationTests.cs
BrokerageApi.Tests/V1/Controllers/AuditControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/AuditEventTests.cs
BrokerageApi.Tests/V1/Factories/ResponseFactoryTest.cs
BrokerageApi.Tests/V1/Gateways/AuditGatewayTests.cs
BrokerageApi/V1/Boundary/Response/AuditEventResponse.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Gateways/AuditGateway.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditEvent.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608120043_ConvertAuditEventMetadataToJsonb.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608120043_ConvertAuditEventMetadataToJsonb.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608123903_AddReferralIdToAuditEvent.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608123903_AddReferralIdToAuditEvent.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608145035_AddReferralRelationshipToAuditEvent.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220608145035_AddReferralRelationshipToAuditEvent.cs
BrokerageApi/V1/Infrastructure/Referral.cs

The design calls for the referral link to use the form name.

Return form name attribute from referral in audit event

---

BrokerageApi/V1/Factories/ResponseFactory.cs

Allow care package to have no elements

Allow care package to have no elements

---

BrokerageApi.Tests/V1/Factories/ResponseFactoryTest.cs
BrokerageApi/V1/Boundary/Response/CarePackageResponse.cs
BrokerageApi/V1/Factories/ResponseFactory.cs

Add yearly estimate to care package response

Add yearly estimate to care package response

---

BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/Helpers/FixtureHelpers.cs
BrokerageApi.Tests/V1/Infrastructure/ElementStatusTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/CancelElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/EndElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/SuspendElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/ApproveCarePackageUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/Mocks/MockAuditGateway.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditMetadataObjects.cs
BrokerageApi/V1/Infrastructure/Element.cs
BrokerageApi/V1/UseCase/CarePackageElements/CancelElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/EndElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/SuspendElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/ApproveCarePackageUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackages/IApproveCarePackageUseCase.cs

https://hackney.atlassian.net/browse/FBT-178
Add endpoint for approving a care package

Fbt 178 approve care package

---

BrokerageApi.Tests/V1/UseCase/CarePackages/StartCarePackageUseCaseTests.cs
BrokerageApi/V1/UseCase/CarePackages/StartCarePackageUseCase.cs

The frontend fires off multiple requests when going to the package builder and currently the first succeeds and the rest fail with a 422 Unprocessable Entity error since it is now in progress. By making the endpoint idempotent these errors are eliminated.

Make package start endpoint idempotent

---

BrokerageApi.Tests/V1/Controllers/CarePackagesControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/Factories/ResponseFactoryTest.cs
BrokerageApi.Tests/V1/Helpers/FixtureHelpers.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/ApproveCarePackageUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/AssignBudgetApproverToCarePackageUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/RequestAmendmentToCarePackageUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Boundary/Request/AmendmentRequest.cs
BrokerageApi/V1/Boundary/Response/AmendmentResponse.cs
BrokerageApi/V1/Boundary/Response/CarePackageResponse.cs
BrokerageApi/V1/Boundary/Response/ReferralResponse.cs
BrokerageApi/V1/Controllers/CarePackagesController.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Gateways/AuditGateway.cs
BrokerageApi/V1/Gateways/CarePackageGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/Infrastructure/AuditEvents/AuditEventType.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/CarePackage.cs
BrokerageApi/V1/Infrastructure/Migrations/20220615100134_CarePackageAmendment.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220615100134_CarePackageAmendment.cs
BrokerageApi/V1/Infrastructure/Referral.cs
BrokerageApi/V1/Infrastructure/ReferralAmendment.cs
BrokerageApi/V1/Infrastructure/ReferralElement.cs
BrokerageApi/V1/UseCase/AssignBudgetApproverToCarePackageUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/ApproveCarePackageUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/RequestAmendmentToCarePackageUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackages/IRequestAmendmentToCarePackageUseCase.cs

Add new endpoint for requesting amendment
https://hackney.atlassian.net/browse/FBT-176

Add new endpooint for requesting amendment

---

data/seeds/element_types.csv

List has been checked over with design.

Final list of element types

---

BrokerageApi.Tests/V1/Controllers/CarePackageElementsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageElementsTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/ResetElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/SuspendElementUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackageElementsController.cs
BrokerageApi/V1/UseCase/CarePackageElements/ResetElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackageElements/IResetElementUseCase.cs

Add end point to reset elements
https://hackney.atlassian.net/browse/FBT-221

Add end point to reset elements

---

BrokerageApi.Tests/V1/Controllers/CarePackageElementsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageElementsTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/ResetElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/SuspendElementUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackageElementsController.cs
BrokerageApi/V1/UseCase/CarePackageElements/CancelElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/ResetElementUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackageElements/IResetElementUseCase.cs

Fix for cancelling a suspension element

Fix cancel suspension element

---

BrokerageApi.Tests/V1/Controllers/CarePackageElementsControllerTests.cs
BrokerageApi.Tests/V1/Controllers/ReferralsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageElementsTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/Gateways/ReferralGatewayTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/ResetElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/SuspendElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/ApproveCarePackageUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CreateReferralUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackageElementsController.cs
BrokerageApi/V1/Controllers/ReferralsController.cs
BrokerageApi/V1/Gateways/Interfaces/IReferralGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/UseCase/CarePackageElements/CancelElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/ResetElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/ApproveCarePackageUseCase.cs
BrokerageApi/V1/UseCase/CreateReferralUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackageElements/IResetElementUseCase.cs

Link existing elements to new referral
End old referrals when referral is approved
https://hackney.atlassian.net/browse/FBT-226

Fbt 226 link existsing elements

---

BrokerageApi.Tests/V1/Controllers/CarePackageElementsControllerTests.cs
BrokerageApi.Tests/V1/Controllers/ReferralsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageElementsTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/E2ETests/ElementsTests.cs
BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/Factories/ResponseFactoryTest.cs
BrokerageApi.Tests/V1/Gateways/ReferralGatewayTests.cs
BrokerageApi.Tests/V1/Helpers/FixtureHelpers.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/ResetElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/SuspendElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/ApproveCarePackageUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CreateReferralUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/CarePackageElementsController.cs
BrokerageApi/V1/Controllers/ReferralsController.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Gateways/Interfaces/IReferralGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/UseCase/CarePackageElements/CancelElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackageElements/ResetElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/ApproveCarePackageUseCase.cs
BrokerageApi/V1/UseCase/CreateReferralUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackageElements/IResetElementUseCase.cs

Return pending fields for suspension elements

Return pending things for suspensions

---

BrokerageApi.Tests/V1/E2ETests/ProviderTests.cs
BrokerageApi.Tests/V1/Gateways/ProviderGatewayTests.cs
BrokerageApi/V1/Gateways/ProviderGateway.cs

https://hackney.atlassian.net/browse/FBT-268

Use custom tsquery builder to improve provider search

---

BrokerageApi.Tests/V1/Controllers/CarePackageElementsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/CarePackageTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackageElements/EndElementUseCaseTests.cs
BrokerageApi.Tests/V1/UseCase/CarePackages/EndCarePackageUseCaseTests.cs
BrokerageApi/V1/Controllers/CarePackageElementsController.cs
BrokerageApi/V1/UseCase/CarePackageElements/EndElementUseCase.cs
BrokerageApi/V1/UseCase/CarePackages/EndCarePackageUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/CarePackageElements/IEndElementUseCase.cs

https://hackney.atlassian.net/browse/FBT-280
A comment is not needed when ending an element so we're taking away the parameter

FBT-280: No comment on ending element

---

BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/UseCase/ArchiveReferralUseCaseTests.cs
BrokerageApi/V1/UseCase/ArchiveReferralUseCase.cs

https://hackney.atlassian.net/jira/software/c/projects/FBT/boards/73?modal=detail&selectedIssue=FBT-302&assignee=617671f0892c4200724d5df3
Allow archiving for assigned and unassigned and in progress referrals

Fbt 302 allow assigned and unassigned to archive

---

BrokerageApi.Tests/V1/Controllers/ReferralsControllerTests.cs
BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi.Tests/V1/Gateways/ReferralGatewayTests.cs
BrokerageApi.Tests/V1/UseCase/GetApprovedReferralsUseCaseTests.cs
BrokerageApi/Startup.cs
BrokerageApi/V1/Controllers/ReferralsController.cs
BrokerageApi/V1/Gateways/Interfaces/IReferralGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/UseCase/GetApprovedReferralsUseCase.cs
BrokerageApi/V1/UseCase/Interfaces/IGetApprovedReferralsUseCase.cs

https://hackney.atlassian.net/browse/FBT-240

Add endpoint to fetch approved referrals awaiting care charges

---

BrokerageApi.Tests/V1/E2ETests/ReferralTests.cs
BrokerageApi/V1/Boundary/Request/CreateReferralRequest.cs
BrokerageApi/V1/Boundary/Response/CarePackageResponse.cs
BrokerageApi/V1/Boundary/Response/ReferralResponse.cs
BrokerageApi/V1/Factories/EntityFactory.cs
BrokerageApi/V1/Factories/ResponseFactory.cs
BrokerageApi/V1/Gateways/CarePackageGateway.cs
BrokerageApi/V1/Gateways/ReferralGateway.cs
BrokerageApi/V1/Infrastructure/BrokerageContext.cs
BrokerageApi/V1/Infrastructure/CarePackage.cs
BrokerageApi/V1/Infrastructure/Migrations/20220712170429_AddWorkflowTable.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220712170429_AddWorkflowTable.cs
BrokerageApi/V1/Infrastructure/Migrations/20220714135553_MigrateWorkflowsData.Designer.cs
BrokerageApi/V1/Infrastructure/Migrations/20220714135553_MigrateWorkflowsData.cs
BrokerageApi/V1/Infrastructure/Referral.cs
BrokerageApi/V1/Infrastructure/Workflow.cs

https://hackney.atlassian.net/browse/FBT-305
Add multiple workflows to a referral or care package

Add multiple workflows to referrals and care packages

---

BrokerageApi.Tests/V1/Factories/ResponseFactoryTest.cs
BrokerageApi/V1/Boundary/Response/WorkflowResponse.cs
BrokerageApi/V1/Factories/ResponseFactory.cs

https://hackney.atlassian.net/browse/FBT-331
Add missing "CreateAt" property to workflow response object

Add CreatedAt property to workflow response
